apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-postgres-deploy
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-postgres-deploy
  target:
    name: postgres-secret
  dataFrom:
    - find:
        name:
          regexp: .*