ingress:
  enabled: true 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: zalando.devops.brentgruber.com
      paths: ["/"]
  tls:
    - secretName: zalando-cert
      hosts:
        - zalando.devops.brentgruber.com