apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-postgres-deploy
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-postgres-deploy
            key: dopplerToken